### ISSUE TITLE
Step 11 (annotate gff files) error

### ISSUE THREAD

**Issue by maepz** [hallamlab/MetaPathways#36]
Hi there,
The pipeline seem to run fine until I reach step 11:
Here is the error from the meta_paths_run_log.txt

![screen shot 2014-02-25 at 3 23 21 pm](https://f.cloud.github.com/assets/6787918/2264543/daa57b58-9e73-11e3-83bb-f8967e0fd393.png)

I run MetaPathways_1_0, on mac OS X 10.9

**Comment by hallamlab** [comment]
Please use the newest version of MP on GitHub
