### ISSUE TITLE
problem running  Gblocks

### ISSUE THREAD

**Issue by danielvalbuenasosa** [hallamlab/MetaPathways#37]
I installed metapathways, but due we have had a versión of glibc, I changed genewise and hmmalign to a compiled/binary version of them (because the ones that comes by default in metapathways only supports glibc.2.14 and we are with glibc2.11 version. When ran the test we get the following error:

COMMAND :
mltreemap/mltreemap_calculation/mltreemap.pl -i test//regression_test/preprocessed//regression_test.fasta -o test//regression_test/mltreemap_calculations/ -e executables/linux/bit64/
Error!:
Start MLTreeMap v2.061
run BLAST
run Genewise
run hmmalign
run Gblocks
ERROR: Can't open test//regression_test/mltreemap_calculations/various_outputs/c_regression_test_8.mfa-gb!

In fact, there there isn't a file with mfa-gb extension:

[user@machine]# ls
c_regression_test_8.mfa                   p_regression_test_6_COG0080_346_603.mfa         regression_test_21_sequence.txt                 regression_test_6_sequence.txt
c_regression_test_8_phocryp_23_789.fa     p_regression_test_6_COG0081_5_310.fa            regression_test_22_blast_result_purified.txt    regression_test_7_blast_result_purified.txt
c_regression_test_8_phocryp_23_789.mfa    p_regression_test_6_COG0081_5_310.mfa           regression_test_22_genewise_result_summary.txt  regression_test_7_COG0085_genewise.txt
h_regression_test_11__K02588_322_851.fa   p_regression_test_6.mfa                         regression_test_22__K02588_genewise.txt         regression_test_7_genewise_result_summary.txt
h_regression_test_11__K02588_322_851.mfa  p_regression_test_7_COG0085_157_873.fa          regression_test_22_sequence_shortened.txt       regression_test_7_sequence_shortened.txt
h_regression_test_11.mfa                  p_regression_test_7_COG0085_157_873.mfa         regression_test_22_sequence.txt                 regression_test_7_sequence.txt
h_regression_test_22__K02588_3_359.fa     p_regression_test_7.mfa                         regression_test_23_blast_result_purified.txt    regression_test_8_blast_result_purified.txt
h_regression_test_22__K02588_3_359.mfa    regression_test_11_blast_result_purified.txt    regression_test_23_genewise_result_summary.txt  regression_test_8_genewise_result_summary.txt
h_regression_test_22.mfa                  regression_test_11_genewise_result_summary.txt  regression_test_23_p_a_moA_genewise.txt         regression_test_8_phocryp_genewise.txt
m_regression_test_23.mfa                  regression_test_11__K02588_genewise.txt         regression_test_23_sequence_shortened.txt       regression_test_8_sequence_shortened.txt
m_regression_test_23_p_a_moA_3_491.fa     regression_test_11_sequence_shortened.txt       regression_test_23_sequence.txt                 regression_test_8_sequence.txt
m_regression_test_23_p_a_moA_3_491.mfa    regression_test_11_sequence.txt                 regression_test_6_blast_result_purified.txt     regression_test.fasta_0BLAST_results_raw.txt
n_regression_test_21__K02586_33_1439.fa   regression_test_21_blast_result_purified.txt    regression_test_6_COG0080_genewise.txt          regression_test.fasta_formated.txt
n_regression_test_21__K02586_33_1439.mfa  regression_test_21_genewise_result_summary.txt  regression_test_6_COG0081_genewise.txt
n_regression_test_21.mfa                  regression_test_21__K02586_genewise.txt         regression_test_6_genewise_result_summary.txt
p_regression_test_6_COG0080_346_603.fa    regression_test_21_sequence_shortened.txt       regression_test_6_sequence_shortened.txt

Appreciate your ideas and comments,

**Comment by ariahahn** [comment]
Please use the newest version of MP available on the hallamlab github repository.

**Comment by hallamlab** [comment]
Please use the newest version of MP on GitHub
